class CreateCoins < ActiveRecord::Migration[5.2]
  def change
    create_table :coins do |t|
			t.string "link_name"
	    t.string "currency_name"
	    t.string "currency_abbrev"
	    t.float "volume_usd"
	    t.float "volume_btc"
	    t.string "picture"
	    t.datetime "created_at", null: false
	    t.datetime "updated_at", null: false
	    t.string "permalink"
	    t.string "genre"
	    t.integer "moderator_id"
	    t.boolean "accepted", default: false
	    t.datetime "accepted_at"
	    t.string "founder"
	    t.string "country_of_origin"
	    t.string "working_product"
	    t.boolean "mineable"
	    t.string "whitepaper"
	    t.string "website"
	    t.string "reddit"
	    t.string "slack"
	    t.string "discord"
	    t.string "app"
	    t.string "github"
	    t.string "tradingview"
	    t.string "twitter"
	    t.string "facebook"
	    t.string "bitcointalk"
	    t.string "stackexchange"
	    t.string "youtube"
	    t.string "coinmarketcap"
	    t.string "gitter"
	    t.string "blockexplorer"
	    t.string "bitfinex"
	    t.string "bithumb"
	    t.string "bitflyer"
	    t.string "hitbtc"
	    t.string "kucoin"
	    t.string "poloniex"
	    t.string "bitstamp"
	    t.string "bittrex"
	    t.string "gdax"
	    t.string "gemini"
	    t.string "btcc"
	    t.string "kraken"
	    t.string "korbit"
	    t.string "binance"
	    t.string "yorbit"
	    t.string "okcoin"
	    t.date "date_of_ico"
	    t.string "telegram"
	    t.string "weibo"
	    t.decimal "money_raised_in_ico"
	    t.integer "genre_id"
	    t.integer "user_id"
	    t.integer "coinmarket_id"
	    t.string "slug"
	    t.boolean "rejected", default: false
	    t.boolean "pending", default: true
	    t.integer "rank"
	    t.decimal "price_usd"
	    t.decimal "price_btc"
	    t.integer "circulating_supply"
	    t.integer "total_supply"
	    t.decimal "market_cap"
	    t.decimal "percent_change_1h"
	    t.decimal "percent_change_24h"
	    t.decimal "percent_change_7d"
	    t.date "end_of_ico"
    	t.index ["slug"], name: "index_coins_on_slug", unique: true
    end
  end
end
